/*
 * Registration-client-api
 *
 * Interage com o registration server (eureka) para registar esta instância ou obter servidores com o qual pode comunicar
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package registration

type Endpoint struct {
	InstanceId string `json:"instanceId,omitempty"`
	Endpoint string `json:"endpoint,omitempty"`
}
